#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Oct 17 16:53:48 EDT 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=rethinking-voxels_r0.1-beta9.zip
