#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Oct 16 17:39:44 EDT 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=rethinking-voxels_r0.1-beta9.zip
